<?php

namespace ContainerAcC2MGW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_7hbEkt2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.7hbEkt2' shared service.
     *
     * @return \App\Http\Requests\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::new()": the $request argument is type-hinted with the non-existent class or interface: "App\\Http\\Requests\\Request".');
    }
}
