<?php

namespace ContainerAcC2MGW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VUnI1J2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vUnI1J2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vUnI1J2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.7hbEkt2', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::new()": the $request argument is type-hinted with the non-existent class or interface: "App\\Http\\Requests\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
