<?php

namespace ContainerO1vqeFt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yx95mwcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yx95mwc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yx95mwc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Group' => ['privates', '.errored..service_locator.Yx95mwc.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.Yx95mwc": it references class "App\\Entity\\Group" but no such service exists.'],
        ], [
            'Group' => 'App\\Entity\\Group',
        ]);
    }
}
