<?php

namespace ContainerO1vqeFt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LVTaT99Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lVTaT99' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lVTaT99'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.yf2Llsg', NULL, 'Cannot determine controller argument for "App\\Controller\\GroupController::new()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
