<?php

namespace ContainerO1vqeFt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZ40vFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HZ40v_F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZ40v_F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'group' => ['privates', '.errored..service_locator.HZ40v_F.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.HZ40v_F": it references class "App\\Entity\\Group" but no such service exists.'],
            'request' => ['privates', '.errored.3apSu9b', NULL, 'Cannot determine controller argument for "App\\Controller\\GroupController::delete()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'group' => 'App\\Entity\\Group',
            'request' => '?',
        ]);
    }
}
