<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1vqeFt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1vqeFt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1vqeFt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1vqeFt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO1vqeFt\App_KernelDevDebugContainer([
    'container.build_hash' => 'O1vqeFt',
    'container.build_id' => '9bb11d31',
    'container.build_time' => 1644618275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1vqeFt');
